### ISSUE TITLE
Upgrade  Mongodb rust driver to  version 3.0.0

### ISSUE THREAD

**Issue by douggynix** [bcortier-devolutions/mongodm-rs#29]
Hi All,
Thanks for this great ODM layer for mongodb rust driver. Is there a plan to move to the new stable release version of rust mongodb driver **3.0.0:**
https://docs.rs/mongodb/3.0.0/mongodb/

There are some breaking changes from rust that may affect this ODM layer. it will be great to have a version of this ODM that's compatible with this one.

Thanks.

**Comment by CBenoit** [comment]
Hi! Thank you!

Yes, we are very likely to move to the new major version in the near future, but I can’t tell you when exactly.
Also, if you have ideas on how this could be achieved, don’t hesitate to send a PR.

cc’ing my colleague @Samuel-B-D

**Comment by douggynix** [comment]
> Hi! Thank you!
> 
> Yes, we are very likely to move to the new major version in the near future, but I can’t tell you when exactly. Also, if you have ideas on how this could be achieved, don’t hesitate to send a PR.
> 
> cc’ing my colleague @Samuel-B-D

Hi, 
I have just opened a PR that we can start working on : https://github.com/Devolutions/mongodm-rs/pull/
A lot of broken changes have been introduced in the new mongodb rust driver. Some methods have been refactored and some errors renamed.
Feel free to have a look at that PR

**Comment by CBenoit** [comment]
Thanks for your help!
